### ISSUE TITLE
Stringy

### ISSUE THREAD

**Issue by Mimia2709** [shebuildsrobots/remy_model#4]
Hi! I saw your video on Instagram and I love it so much. I’ve attempted to print Remy multiple times (photos attached) but I’m having a really hard time getting it to work. I have a Bambu Lab P1S 3D Printer. I’ve seen that once it gets to the nose area, the filament becomes stringy and won’t form as supposed to. Is there anyway you can help me with this? My last try was the one with the tree supports and I’m not sure that worked much better. Thanks. 

![image](https://github.com/user-attachments/assets/628a087e-f13f-4df7-81bc-170f28449e00)
![image](https://github.com/user-attachments/assets/02190fa9-7953-41ce-a91d-fa9005384c46)
![image](https://github.com/user-attachments/assets/1a3a1b9f-ae07-449b-b29d-86853e2a293c)

**Comment by shebuildsrobots** [comment]
Hi! I haven't heard reports of this happening for anyone else -- maybe someone else browsing will have advice? I sliced my model with UltiMaker with Supports toggled on, and printed using the Engineering setting. I hope that helps troubleshoot. Good luck!

**Comment by brandanop** [comment]
I printed mine successfully on a Bambu labs A1 with AMS for multicolor. I would recommend making sure your filament is dry and running the calibration. I also used the same supports. If that doesn’t work, maybe try rotating it to make Remy lay on his back with supports?
![IMG_3503](https://github.com/user-attachments/assets/01165199-7ece-443a-9903-710a47290d7b)

**Comment by bengalaviz** [comment]
I have a Prusa MINI and had to print with supports also. 
<img width="373" alt="image" src="https://github.com/user-attachments/assets/cdb778c0-4d8e-4186-95db-acdef4c7974b">

**Comment by Mimia2709** [comment]
Thank you so much. I got it to work!
